/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDataServiceApiUploadTarget.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API
// Classes:
//   GTLDataServiceApiUploadTarget (0 custom class methods, 1 custom properties)

#import "GTLDataServiceApiUploadTarget.h"

// ----------------------------------------------------------------------------
//
//   GTLDataServiceApiUploadTarget
//

@implementation GTLDataServiceApiUploadTarget
@dynamic url;
@end
