/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDataServiceApiGroupVoca.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API
// Classes:
//   GTLDataServiceApiGroupVoca (0 custom class methods, 4 custom properties)

#import "GTLDataServiceApiGroupVoca.h"

// ----------------------------------------------------------------------------
//
//   GTLDataServiceApiGroupVoca
//

@implementation GTLDataServiceApiGroupVoca
@dynamic creator, descriptionProperty, identifier, listVoca;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"descriptionProperty" : @"description",
    @"identifier" : @"id"
  };
  return map;
}

@end
