/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDataServiceApiVoca.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API
// Classes:
//   GTLDataServiceApiVoca (0 custom class methods, 11 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLDataServiceApiVoca
//

@interface GTLDataServiceApiVoca : GTLObject
@property (nonatomic, copy) NSString *a;
@property (nonatomic, retain) NSNumber *check;  // boolValue
@property (nonatomic, copy) NSString *creator;
@property (nonatomic, retain) NSNumber *gid;  // longLongValue
@property (nonatomic, copy) NSString *lEn;
@property (nonatomic, copy) NSString *lVn;
@property (nonatomic, retain) NSNumber *level;  // intValue
@property (nonatomic, copy) NSString *note;
@property (nonatomic, copy) NSString *packages;
@property (nonatomic, copy) NSString *q;
@property (nonatomic, copy) NSString *userComment;
@end
