/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLDataServiceApiDownloadTarget.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API
// Classes:
//   GTLDataServiceApiDownloadTarget (0 custom class methods, 1 custom properties)

#import "GTLDataServiceApiDownloadTarget.h"

// ----------------------------------------------------------------------------
//
//   GTLDataServiceApiDownloadTarget
//

@implementation GTLDataServiceApiDownloadTarget
@dynamic url;
@end
