/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryDataServiceApi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API
// Classes:
//   GTLQueryDataServiceApi (10 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLDataServiceApiVoca;

@interface GTLQueryDataServiceApi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, copy) NSString *code;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (nonatomic, assign) long long identifier;
@property (nonatomic, assign) BOOL orderSearch;
@property (nonatomic, copy) NSString *q;

#pragma mark - Service level methods
// These create a GTLQueryDataServiceApi object.

// Method: dataServiceApi.findVocaById
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
// Fetches a GTLDataServiceApiVoca.
+ (instancetype)queryForFindVocaByIdWithIdentifier:(long long)identifier
                                       orderSearch:(BOOL)orderSearch;

// Method: dataServiceApi.findVocaByQ
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
// Fetches a GTLDataServiceApiVoca.
+ (instancetype)queryForFindVocaByQWithOrderSearch:(BOOL)orderSearch
                                                 q:(NSString *)q;

// Method: dataServiceApi.getDownloadUrl
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
// Fetches a GTLDataServiceApiDownloadTarget.
+ (instancetype)queryForGetDownloadUrlWithCode:(NSString *)code;

// Method: dataServiceApi.getUploadUrl
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
// Fetches a GTLDataServiceApiUploadTarget.
+ (instancetype)queryForGetUploadUrl;

// Method: dataServiceApi.getVocaById
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
// Fetches a GTLDataServiceApiVoca.
+ (instancetype)queryForGetVocaByIdWithIdentifier:(long long)identifier;

// Method: dataServiceApi.getVocaByQ
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
// Fetches a GTLDataServiceApiVoca.
+ (instancetype)queryForGetVocaByQWithQ:(NSString *)q;

// Method: dataServiceApi.listVoca
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
// Fetches a GTLDataServiceApiVocaCollection.
+ (instancetype)queryForListVoca;

// Method: dataServiceApi.saveVoca
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
+ (instancetype)queryForSaveVocaWithObject:(GTLDataServiceApiVoca *)object;

// Method: dataServiceApi.updateA
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
+ (instancetype)queryForUpdateAWithObject:(GTLDataServiceApiVoca *)object;

// Method: dataServiceApi.updateD
//  Authorization scope(s):
//   kGTLAuthScopeDataServiceApiUserinfoEmail
+ (instancetype)queryForUpdateDWithObject:(GTLDataServiceApiVoca *)object;

@end
