// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRDataServiceApi_Voca;

NS_ASSUME_NONNULL_BEGIN

/**
 *  GTLRDataServiceApi_DownloadTarget
 */
@interface GTLRDataServiceApi_DownloadTarget : GTLRObject

@property(nonatomic, copy, nullable) NSString *url;

@end


/**
 *  GTLRDataServiceApi_GroupVoca
 */
@interface GTLRDataServiceApi_GroupVoca : GTLRObject

@property(nonatomic, copy, nullable) NSString *creator;

/**
 *  descriptionProperty
 *
 *  Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
 */
@property(nonatomic, copy, nullable) NSString *descriptionProperty;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *identifier;

@property(nonatomic, copy, nullable) NSString *listVoca;

@end


/**
 *  GTLRDataServiceApi_UploadTarget
 */
@interface GTLRDataServiceApi_UploadTarget : GTLRObject

@property(nonatomic, copy, nullable) NSString *url;

@end


/**
 *  GTLRDataServiceApi_Voca
 */
@interface GTLRDataServiceApi_Voca : GTLRObject

@property(nonatomic, copy, nullable) NSString *a;

/**
 *  check
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *check;

@property(nonatomic, copy, nullable) NSString *creator;

/**
 *  gid
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *gid;

@property(nonatomic, copy, nullable) NSString *lEn;
@property(nonatomic, copy, nullable) NSString *lVn;

/**
 *  level
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *level;

@property(nonatomic, copy, nullable) NSString *note;
@property(nonatomic, copy, nullable) NSString *packages;
@property(nonatomic, copy, nullable) NSString *q;
@property(nonatomic, copy, nullable) NSString *userComment;

@end


/**
 *  GTLRDataServiceApi_VocaCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRDataServiceApi_VocaCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRDataServiceApi_Voca *> *items;

@end

NS_ASSUME_NONNULL_END
