// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API

#import "GTLRDataServiceApi.h"

// ----------------------------------------------------------------------------
// Authorization scope

NSString * const kGTLRAuthScopeDataServiceApiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// ----------------------------------------------------------------------------
//   GTLRDataServiceApiService
//

@implementation GTLRDataServiceApiService

- (instancetype)init {
  self = [super init];
  if (self) {
    // From discovery.
    self.rootURLString = @"https://lazeebee-977.appspot.com/_ah/api/";
    self.servicePath = @"dataServiceApi/v1.1/";
    self.batchPath = @"batch";
    self.prettyPrintQueryParameterNames = @[ @"prettyPrint" ];
  }
  return self;
}

@end
