// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API

#import "GTLRDataServiceApiObjects.h"

// ----------------------------------------------------------------------------
//
//   GTLRDataServiceApi_DownloadTarget
//

@implementation GTLRDataServiceApi_DownloadTarget
@dynamic url;
@end


// ----------------------------------------------------------------------------
//
//   GTLRDataServiceApi_GroupVoca
//

@implementation GTLRDataServiceApi_GroupVoca
@dynamic creator, descriptionProperty, identifier, listVoca;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"descriptionProperty" : @"description",
    @"identifier" : @"id"
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRDataServiceApi_UploadTarget
//

@implementation GTLRDataServiceApi_UploadTarget
@dynamic url;
@end


// ----------------------------------------------------------------------------
//
//   GTLRDataServiceApi_Voca
//

@implementation GTLRDataServiceApi_Voca
@dynamic a, check, creator, gid, lEn, lVn, level, note, packages, q,
         userComment;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  NSDictionary<NSString *, NSString *> *map = @{
    @"lEn" : @"l_en",
    @"lVn" : @"l_vn",
    @"userComment" : @"user_comment"
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRDataServiceApi_VocaCollection
//

@implementation GTLRDataServiceApi_VocaCollection
@dynamic items;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRDataServiceApi_Voca class]
  };
  return map;
}

@end
