// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   LazzyBee Backend Api (dataServiceApi/v1.1)
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRQuery.h"
#else
  #import "GTLRQuery.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRDataServiceApi_Voca;

NS_ASSUME_NONNULL_BEGIN

/**
 *  Parent class for other DataServiceApi query classes.
 */
@interface GTLRDataServiceApiQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  GTLRDataServiceApiQuery_FindVocaById
 *
 *  Method: dataServiceApi.findVocaById
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_FindVocaById : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForFindVocaByIdWithidentifier:orderSearch:]

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, assign) long long identifier;

@property(nonatomic, assign) BOOL orderSearch;

/**
 *  Fetches a @c GTLRDataServiceApi_Voca.
 *
 *  @param identifier long long
 *  @param orderSearch BOOL
 *
 *  @returns GTLRDataServiceApiQuery_FindVocaById
 */
+ (instancetype)queryWithIdentifier:(long long)identifier
                        orderSearch:(BOOL)orderSearch;

@end

/**
 *  GTLRDataServiceApiQuery_FindVocaByQ
 *
 *  Method: dataServiceApi.findVocaByQ
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_FindVocaByQ : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForFindVocaByQWithorderSearch:q:]

@property(nonatomic, assign) BOOL orderSearch;

@property(nonatomic, copy, nullable) NSString *q;

/**
 *  Fetches a @c GTLRDataServiceApi_Voca.
 *
 *  @param orderSearch BOOL
 *  @param q NSString
 *
 *  @returns GTLRDataServiceApiQuery_FindVocaByQ
 */
+ (instancetype)queryWithOrderSearch:(BOOL)orderSearch
                                   q:(NSString *)q;

@end

/**
 *  GTLRDataServiceApiQuery_GetDownloadUrl
 *
 *  Method: dataServiceApi.getDownloadUrl
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_GetDownloadUrl : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForGetDownloadUrlWithcode:]

@property(nonatomic, copy, nullable) NSString *code;

/**
 *  Fetches a @c GTLRDataServiceApi_DownloadTarget.
 *
 *  @param code NSString
 *
 *  @returns GTLRDataServiceApiQuery_GetDownloadUrl
 */
+ (instancetype)queryWithCode:(NSString *)code;

@end

/**
 *  GTLRDataServiceApiQuery_GetGroupVoca
 *
 *  Method: dataServiceApi.getGroupVoca
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_GetGroupVoca : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForGetGroupVocaWithidentifier:]

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, assign) long long identifier;

/**
 *  Fetches a @c GTLRDataServiceApi_GroupVoca.
 *
 *  @param identifier long long
 *
 *  @returns GTLRDataServiceApiQuery_GetGroupVoca
 */
+ (instancetype)queryWithIdentifier:(long long)identifier;

@end

/**
 *  GTLRDataServiceApiQuery_GetUploadUrl
 *
 *  Method: dataServiceApi.getUploadUrl
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_GetUploadUrl : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForGetUploadUrl]

/**
 *  Fetches a @c GTLRDataServiceApi_UploadTarget.
 *
 *  @returns GTLRDataServiceApiQuery_GetUploadUrl
 */
+ (instancetype)query;

@end

/**
 *  GTLRDataServiceApiQuery_GetVocaById
 *
 *  Method: dataServiceApi.getVocaById
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_GetVocaById : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForGetVocaByIdWithidentifier:]

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 */
@property(nonatomic, assign) long long identifier;

/**
 *  Fetches a @c GTLRDataServiceApi_Voca.
 *
 *  @param identifier long long
 *
 *  @returns GTLRDataServiceApiQuery_GetVocaById
 */
+ (instancetype)queryWithIdentifier:(long long)identifier;

@end

/**
 *  GTLRDataServiceApiQuery_GetVocaByQ
 *
 *  Method: dataServiceApi.getVocaByQ
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_GetVocaByQ : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForGetVocaByQWithq:]

@property(nonatomic, copy, nullable) NSString *q;

/**
 *  Fetches a @c GTLRDataServiceApi_Voca.
 *
 *  @param q NSString
 *
 *  @returns GTLRDataServiceApiQuery_GetVocaByQ
 */
+ (instancetype)queryWithQ:(NSString *)q;

@end

/**
 *  GTLRDataServiceApiQuery_ListVoca
 *
 *  Method: dataServiceApi.listVoca
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_ListVoca : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForListVocaWithcursorStr:level:size:]

@property(nonatomic, copy, nullable) NSString *cursorStr;

@property(nonatomic, assign) NSInteger level;

@property(nonatomic, assign) NSInteger size;

/**
 *  Fetches a @c GTLRDataServiceApi_VocaCollection.
 *
 *  @param cursorStr NSString
 *  @param level NSInteger
 *  @param size NSInteger
 *
 *  @returns GTLRDataServiceApiQuery_ListVoca
 */
+ (instancetype)queryWithCursorStr:(NSString *)cursorStr
                             level:(NSInteger)level
                              size:(NSInteger)size;

@end

/**
 *  GTLRDataServiceApiQuery_SaveVoca
 *
 *  Method: dataServiceApi.saveVoca
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_SaveVoca : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForSaveVocaWithObject:]

/**
 *  Upon successful completion, the callback's object and error parameters will
 *  be nil. This query does not fetch an object.
 *
 *  @param object The @c GTLRDataServiceApi_Voca to include in the query.
 *
 *  @returns GTLRDataServiceApiQuery_SaveVoca
 */
+ (instancetype)queryWithObject:(GTLRDataServiceApi_Voca *)object;

@end

/**
 *  GTLRDataServiceApiQuery_UpdateA
 *
 *  Method: dataServiceApi.updateA
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_UpdateA : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForUpdateAWithObject:]

/**
 *  Upon successful completion, the callback's object and error parameters will
 *  be nil. This query does not fetch an object.
 *
 *  @param object The @c GTLRDataServiceApi_Voca to include in the query.
 *
 *  @returns GTLRDataServiceApiQuery_UpdateA
 */
+ (instancetype)queryWithObject:(GTLRDataServiceApi_Voca *)object;

@end

/**
 *  GTLRDataServiceApiQuery_UpdateD
 *
 *  Method: dataServiceApi.updateD
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_UpdateD : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForUpdateDWithObject:]

/**
 *  Upon successful completion, the callback's object and error parameters will
 *  be nil. This query does not fetch an object.
 *
 *  @param object The @c GTLRDataServiceApi_Voca to include in the query.
 *
 *  @returns GTLRDataServiceApiQuery_UpdateD
 */
+ (instancetype)queryWithObject:(GTLRDataServiceApi_Voca *)object;

@end

/**
 *  GTLRDataServiceApiQuery_UpdateEDict
 *
 *  Method: dataServiceApi.updateEDict
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_UpdateEDict : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForUpdateEDictWithObject:]

/**
 *  Upon successful completion, the callback's object and error parameters will
 *  be nil. This query does not fetch an object.
 *
 *  @param object The @c GTLRDataServiceApi_Voca to include in the query.
 *
 *  @returns GTLRDataServiceApiQuery_UpdateEDict
 */
+ (instancetype)queryWithObject:(GTLRDataServiceApi_Voca *)object;

@end

/**
 *  GTLRDataServiceApiQuery_UpdateVDict
 *
 *  Method: dataServiceApi.updateVDict
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeDataServiceApiUserinfoEmail
 */
@interface GTLRDataServiceApiQuery_UpdateVDict : GTLRDataServiceApiQuery
// Previous library name was
//   +[GTLQueryDataServiceApi queryForUpdateVDictWithObject:]

/**
 *  Upon successful completion, the callback's object and error parameters will
 *  be nil. This query does not fetch an object.
 *
 *  @param object The @c GTLRDataServiceApi_Voca to include in the query.
 *
 *  @returns GTLRDataServiceApiQuery_UpdateVDict
 */
+ (instancetype)queryWithObject:(GTLRDataServiceApi_Voca *)object;

@end

NS_ASSUME_NONNULL_END
